"""Controlled UV-parameter sensitivity trajectories for the T3 benchmark.

The three scaling directions preserve the leading T3 neutrino-mass prefactor

    lambdaT3 * (y1 y2 + y2 y1)

at the input scale for positive real gamma:

T1:
    lambdaT3 -> gamma lambdaT3
    y1 -> gamma^(-1/2) y1
    y2 -> gamma^(-1/2) y2

T2:
    lambdaT3 -> gamma lambdaT3
    y2 -> gamma^(-1) y2

T3:
    y1 -> gamma y1
    y2 -> gamma^(-1) y2

Any displacement of low-energy neutrino observables along these directions is
therefore generated by different RG evolution and threshold dependence, not by
a trivial overall rescaling of the leading input prefactor.

Each point is evaluated through the existing numerical T3 trajectory and
final-C5 evaluator. No new matching formula is introduced.
"""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Mapping

import numpy as np

from Numerical.FinalC5TrajectoryAdapter import FinalC5TrajectoryEvaluator
from Numerical.OscillationFit import OscillationFitTarget
from Numerical.ParameterScan import make_t3_point_evaluator
from Numerical.RGBetaEvaluator import load_rgbeta_payload
from Numerical.ScanCLI import build_uv_state_from_config


def _scale_complex_matrix_spec(spec: dict[str, Any], factor: float) -> None:
    factor = float(factor)
    real = np.asarray(spec["real"], dtype=float)
    imag = np.asarray(spec.get("imag", np.zeros_like(real)), dtype=float)
    spec["real"] = (real * factor).tolist()
    spec["imag"] = (imag * factor).tolist()


def _scale_complex_scalar_spec(spec: dict[str, Any], factor: float) -> None:
    factor = float(factor)
    spec["real"] = float(spec.get("real", 0.0)) * factor
    spec["imag"] = float(spec.get("imag", 0.0)) * factor


def scaled_config_payload(
    payload: Mapping[str, Any],
    direction: str,
    gamma: float,
) -> dict[str, Any]:
    """Return one T3-specific scaling deformation of the benchmark config."""

    gamma = float(gamma)
    if not np.isfinite(gamma) or gamma <= 0.0:
        raise ValueError("gamma must be finite and positive.")

    direction = str(direction).upper()
    if direction not in {"T1", "T2", "T3"}:
        raise ValueError("direction must be T1, T2 or T3.")

    result = deepcopy(dict(payload))
    ordinary = result["base_state"]["ordinary"]

    if direction == "T1":
        _scale_complex_scalar_spec(ordinary["lambdaT3"], gamma)
        inverse_root = gamma ** -0.5
        _scale_complex_matrix_spec(ordinary["y1"], inverse_root)
        _scale_complex_matrix_spec(ordinary["y2"], inverse_root)
    elif direction == "T2":
        _scale_complex_scalar_spec(ordinary["lambdaT3"], gamma)
        _scale_complex_matrix_spec(ordinary["y2"], gamma ** -1.0)
    else:
        _scale_complex_matrix_spec(ordinary["y1"], gamma)
        _scale_complex_matrix_spec(ordinary["y2"], gamma ** -1.0)

    return result


def leading_prefactor_scale(direction: str, gamma: float) -> float:
    """Return the multiplicative scaling of lambdaT3*y1*y2."""

    gamma = float(gamma)
    direction = str(direction).upper()

    if direction == "T1":
        return gamma * gamma ** -0.5 * gamma ** -0.5
    if direction == "T2":
        return gamma * gamma ** -1.0
    if direction == "T3":
        return gamma * gamma ** -1.0
    raise ValueError("direction must be T1, T2 or T3.")


def _config_view(payload: Mapping[str, Any]) -> SimpleNamespace:
    raw = deepcopy(dict(payload))
    raw.setdefault("scan", {"bindings": {}})
    return SimpleNamespace(raw=raw)


def run_t3_sensitivity_scan(
    *,
    base_payload: Mapping[str, Any],
    uv_rgbeta_path: Path,
    intermediate_rgbeta_path: Path,
    final_weinberg_path: Path,
    oscillation_target_path: Path,
) -> dict[str, Any]:
    """Evaluate the configured T1/T2/T3 sensitivity trajectories."""

    sensitivity = base_payload.get("sensitivity", {})
    if not isinstance(sensitivity, Mapping):
        raise ValueError("sensitivity must be an object.")

    if not bool(sensitivity.get("enabled", True)):
        return {"status": "Disabled"}

    gamma_min = float(sensitivity.get("gamma_min", 0.95))
    gamma_max = float(sensitivity.get("gamma_max", 1.05))
    n_points = int(sensitivity.get("n_points", 11))

    if not (0.0 < gamma_min < gamma_max):
        raise ValueError("Require 0 < gamma_min < gamma_max.")
    if n_points < 3:
        raise ValueError("sensitivity.n_points must be at least 3.")

    gammas = np.linspace(gamma_min, gamma_max, n_points)
    uv_rgbeta = load_rgbeta_payload(Path(uv_rgbeta_path))
    intermediate_rgbeta = load_rgbeta_payload(Path(intermediate_rgbeta_path))
    target = OscillationFitTarget.from_json(Path(oscillation_target_path))

    scales = base_payload["scales"]
    numerical = base_payload.get("numerical", {})
    mu_f = float(scales["mu_fermion_threshold_gev"])
    mu_s = float(scales["mu_scalar_threshold_gev"])
    mu_low = float(scales["mu_low_gev"])
    vev = float(numerical.get("vev_gev", 246.22))
    rtol = float(numerical.get("rtol", 1.0e-8))
    atol = float(numerical.get("atol", 1.0e-11))

    c5_evaluator = FinalC5TrajectoryEvaluator(Path(final_weinberg_path))
    results: dict[str, list[dict[str, Any]]] = {}

    for direction in ("T1", "T2", "T3"):
        points: list[dict[str, Any]] = []

        for gamma in gammas:
            deformed = scaled_config_payload(
                base_payload,
                direction,
                float(gamma),
            )
            view = _config_view(deformed)

            evaluator = make_t3_point_evaluator(
                uv_state_builder=lambda _params, view=view: build_uv_state_from_config(
                    view,
                    {},
                ),
                c5_builder=c5_evaluator,
                uv_rgbeta_payload=uv_rgbeta,
                eft1_rgbeta_payload=intermediate_rgbeta,
                target=target,
                mu_fermion_threshold_gev=mu_f,
                mu_scalar_threshold_gev=mu_s,
                mu_low_gev=mu_low,
                vev_gev=vev,
                rtol=rtol,
                atol=atol,
            )

            fit = evaluator({})
            prediction = {
                name: float(value)
                for name, value in zip(
                    fit.observable_names,
                    fit.prediction,
                )
            }

            points.append(
                {
                    "gamma": float(gamma),
                    "chi2": float(fit.chi2),
                    "prediction": prediction,
                }
            )

        results[direction] = points

    return {
        "status": "Success",
        "gamma_min": gamma_min,
        "gamma_max": gamma_max,
        "n_points": n_points,
        "directions": {
            "T1": {
                "definition": (
                    "lambdaT3 -> gamma lambdaT3; "
                    "y1,y2 -> gamma^(-1/2) y1,y2"
                ),
                "points": results["T1"],
            },
            "T2": {
                "definition": (
                    "lambdaT3 -> gamma lambdaT3; "
                    "y2 -> gamma^(-1) y2"
                ),
                "points": results["T2"],
            },
            "T3": {
                "definition": (
                    "y1 -> gamma y1; y2 -> gamma^(-1) y2"
                ),
                "points": results["T3"],
            },
        },
        "target": {
            "ordering": target.ordering,
            "observable_names": list(target.observable_names),
            "central_values": target.central_values.tolist(),
            "covariance": target.covariance.tolist(),
            "source": target.source,
            "note": (
                "The configured target is a Gaussian approximation. The plotted "
                "1sigma/3sigma regions are Gaussianized regions, not official "
                "Delta-chi2 contours."
            ),
        },
    }
