from __future__ import annotations

"""Component-level one-loop RGE for the EFT after integrating out F.

This stage combines the already validated ingredients

    C_ijab^(0)          from EFT1WilsonAdapter
    lambda_abcd         from EFT1QuarticAdapter
    SM Yukawa tensor    from MatchedEFTRGE
    SU(2)xU(1) generators from the general RGE machinery

and evaluates the complete one-loop master equation for psi^2 phi^2
operators.

Fixed-order bookkeeping:
    only the tree-generated EFT1 Wilson tensor C^(0) is evolved here.
    The one-loop stage-1 matching contribution is a boundary term and is not
    fed into this one-loop anomalous dimension.

The default output scan is the one-loop closure relevant to a tree-level
LL scalar-scalar operator under SM Yukawas: L and eC external fermions, with
all real scalar pairs.  This includes zero-at-boundary components that are
generated by mixing.  Use --seed-support-only for a fast plumbing test.

The output is deliberately component-level.  Projection back onto an
independent gauge-invariant operator basis is a later reporting step.
"""

from dataclasses import dataclass
from itertools import combinations_with_replacement
import json
from pathlib import Path
import sys
import time

# Allow this file to be run directly from the repository root with
#
#     python RGE/running/EFT1WilsonRGE.py ...
#
# while keeping package-style imports below.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import sympy as sp

from RGE.general.AnomalousDimensions import calculate_complete_master_rge
from RGE.general.MasterWeinbergRGE import MasterRGEInputs
from RGE.general.RGEModel import RGEModel
from RGE.matching.MatchedEFTRGE import build_sm_eft, build_sm_yukawa
from RGE.running.EFT1QuarticAdapter import (
    load_and_build_eft1_quartic_tensor,
)
from RGE.running.EFT1WilsonAdapter import (
    load_and_build_eft1_wilson_tensor,
)
from tests.non_pipeline_rge.general.FermionBasis import build_gauge_sectors
from tests.non_pipeline_rge.general.T3RGETensors import SparseWilsonLookup
from tests.python.Weinberg.WeinbergWilsonAdapter import (
    build_weinberg_wilson_tensor,
)


@dataclass(frozen=True)
class EFT1RGEContext:
    model: RGEModel
    fermion_basis: object
    coefficient: object
    quartic: object
    inputs: MasterRGEInputs
    metadata: dict


def _parse_rational(value) -> sp.Rational:
    """Parse Matchete/RGBeta metadata values such as '-1/2' exactly."""
    if isinstance(value, int):
        return sp.Rational(value)
    return sp.Rational(str(value))


def _canonical_component(
    component: tuple[int, int, int, int],
) -> tuple[int, int, int, int]:
    i, j, a, b = component
    return (min(i, j), max(i, j), min(a, b), max(a, b))


def _symmetry_residual_count(coefficient) -> int:
    failures = 0
    keys = set(coefficient.entries)
    for i, j, a, b in tuple(keys):
        keys.update(
            {
                (j, i, a, b),
                (i, j, b, a),
                (j, i, b, a),
            }
        )
    for i, j, a, b in keys:
        reference = coefficient[i, j, a, b]
        if sp.simplify(reference - coefficient[j, i, a, b]) != 0:
            failures += 1
        if sp.simplify(reference - coefficient[i, j, b, a]) != 0:
            failures += 1
    return failures


def build_eft1_rge_context(
    wilson_seed_path: Path,
    quartic_seed_path: Path,
    rgbeta_path: Path,
) -> EFT1RGEContext:
    rgbeta = json.loads(Path(rgbeta_path).read_text(encoding="utf-8"))
    metadata = rgbeta["metadata"]

    d_s1 = int(metadata["dS1"])
    d_s2 = int(metadata["dS2"])
    y_s1 = _parse_rational(metadata["YS1"])
    y_s2 = _parse_rational(metadata["YS2"])

    scalar_model = RGEModel.t3(
        d_s1=d_s1,
        y_s1=y_s1,
        d_s2=d_s2,
        y_s2=y_s2,
        include_higgs=True,
    )

    # Reuse the validated one-generation SM Weyl basis.  F is absent in EFT1;
    # S1 and S2 are scalars, so the active fermion basis is exactly the SM one.
    _, fermion_basis = build_sm_eft()

    l1 = fermion_basis.global_index("L", 1)
    l2 = fermion_basis.global_index("L", 2)

    coefficient = load_and_build_eft1_wilson_tensor(
        wilson_seed_path,
        rgbeta_path,
        chirality="PL",
        lepton_indices=(l1, l2),
        project_operator_symmetry=True,
    )

    residual_count = _symmetry_residual_count(coefficient)
    if residual_count:
        raise RuntimeError(
            "Projected EFT1 Wilson tensor is not separately symmetric: "
            f"{residual_count} residual(s)."
        )

    quartic = load_and_build_eft1_quartic_tensor(
        quartic_seed_path,
        rgbeta_path,
    )

    yukawa = build_sm_yukawa(
        scalar_model,
        fermion_basis,
    )

    inputs = MasterRGEInputs(
        fermion_dimension=fermion_basis.dimension,
        yukawa=yukawa,
        quartic=quartic,
        gauge_sectors=build_gauge_sectors(
            scalar_model,
            fermion_basis,
        ),
    )

    return EFT1RGEContext(
        model=scalar_model,
        fermion_basis=fermion_basis,
        coefficient=coefficient,
        quartic=quartic,
        inputs=inputs,
        metadata=metadata,
    )


def seed_support_components(context: EFT1RGEContext):
    """Canonical independent components already nonzero at the F threshold."""
    return sorted(
        {
            _canonical_component(component)
            for component, value in context.coefficient.nonzero_items()
            if sp.simplify(value) != 0
        }
    )


def closure_output_components(context: EFT1RGEContext):
    """Independent output components relevant to LL seed mixing at one loop.

    The only SM Yukawa partner of the lepton doublet L is eC.  Hence the
    fermionic closure of a tree-level LL coefficient is contained in
    {L_1, L_2, eC}; internal sums still run over the entire SM fermion basis
    and therefore retain quark Yukawa trace effects.

    All scalar pairs are retained because quartic mixing can move the Wilson
    coefficient among H, S1 and S2 sectors.
    """

    fb = context.fermion_basis
    fermions = sorted(
        {
            fb.global_index("L", 1),
            fb.global_index("L", 2),
            fb.global_index("eC", 1),
        }
    )
    scalars = range(1, context.model.total_real_scalar_dimension + 1)

    return [
        (i, j, a, b)
        for i, j in combinations_with_replacement(fermions, 2)
        for a, b in combinations_with_replacement(scalars, 2)
    ]


def calculate_component_betas(
    context: EFT1RGEContext,
    *,
    seed_support_only: bool = False,
    simplify_each: bool = False,
) -> dict[tuple[int, int, int, int], dict[str, sp.Expr]]:
    """Evaluate the complete one-loop beta tensor on an independent component set."""

    components = (
        seed_support_components(context)
        if seed_support_only
        else closure_output_components(context)
    )

    result: dict[
        tuple[int, int, int, int],
        dict[str, sp.Expr],
    ] = {}

    for component in components:
        contributions = calculate_complete_master_rge(
            model=context.model,
            inputs=context.inputs,
            output_component=component,
            coefficient=context.coefficient,
            simplify_each=simplify_each,
        )

        total = sp.simplify(contributions["total"])
        if total != 0:
            # Store a simplified total but preserve the named structural
            # contributions for later report decomposition.
            result[component] = {
                **contributions,
                "total": total,
            }

    return result


def _expr_text(expression: sp.Expr) -> str:
    return sp.sstr(sp.factor(sp.simplify(expression)))


def _serialise_component(component) -> str:
    return ",".join(str(index) for index in component)



def weinberg_subspace_diagnostics(
    context: EFT1RGEContext,
    betas: dict[tuple[int, int, int, int], dict[str, sp.Expr]],
) -> dict:
    """Check whether the generated LL-HH beta is exactly a Weinberg operator.

    This uses the already benchmarked WeinbergWilsonAdapter as the normalization
    template.  With template kappa=1, a proportionality factor r means

        16*pi^2 d(kappa)/dln(mu) = r

    for the part generated by EFT1 running.
    """

    sm_scalar_model, sm_fermion_basis = build_sm_eft()

    if sm_fermion_basis.dimension != context.fermion_basis.dimension:
        raise RuntimeError("SM benchmark fermion basis does not match EFT1 basis.")

    template_dict = build_weinberg_wilson_tensor(
        sm_scalar_model,
        sm_fermion_basis,
        sp.S.One,
    )
    template = SparseWilsonLookup(template_dict)

    l1 = context.fermion_basis.global_index("L", 1)
    l2 = context.fermion_basis.global_index("L", 2)
    h_indices = tuple(sm_scalar_model.block("H").indices)

    components = [
        (i, j, a, b)
        for i, j in combinations_with_replacement((l1, l2), 2)
        for a, b in combinations_with_replacement(h_indices, 2)
    ]

    def beta_value(component):
        return sp.simplify(
            betas.get(_canonical_component(component), {}).get(
                "total",
                sp.S.Zero,
            )
        )

    template_nonzero = [
        component
        for component in components
        if sp.simplify(template[component]) != 0
    ]

    if not template_nonzero:
        raise RuntimeError("Weinberg normalization template has no nonzero components.")

    reference_component = template_nonzero[0]
    beta_kappa = sp.simplify(
        beta_value(reference_component) / template[reference_component]
    )

    failures = {}
    for component in components:
        expected = sp.simplify(beta_kappa * template[component])
        residual = sp.simplify(beta_value(component) - expected)
        if residual != 0:
            failures[_serialise_component(component)] = _expr_text(residual)

    return {
        "matches_weinberg_subspace": not failures,
        "failure_count": len(failures),
        "template_nonzero_component_count": len(template_nonzero),
        "reference_component": list(reference_component),
        "beta_kappa_16pi2": _expr_text(beta_kappa),
        "residuals": failures,
    }


def run_eft1_wilson_rge(
    wilson_seed_path: Path,
    quartic_seed_path: Path,
    rgbeta_path: Path,
    output_path: Path | None = None,
    *,
    seed_support_only: bool = False,
) -> dict:
    started = time.perf_counter()

    context = build_eft1_rge_context(
        wilson_seed_path=wilson_seed_path,
        quartic_seed_path=quartic_seed_path,
        rgbeta_path=rgbeta_path,
    )

    candidates = (
        seed_support_components(context)
        if seed_support_only
        else closure_output_components(context)
    )

    betas = calculate_component_betas(
        context,
        seed_support_only=seed_support_only,
        simplify_each=False,
    )

    initial_support = {
        _canonical_component(component)
        for component, value in context.coefficient.nonzero_items()
        if sp.simplify(value) != 0
    }

    generated = sorted(
        component
        for component in betas
        if component not in initial_support
    )

    weinberg_diagnostics = (
        None
        if seed_support_only
        else weinberg_subspace_diagnostics(context, betas)
    )

    elapsed = time.perf_counter() - started

    payload = {
        "status": "Success",
        "theory": "SM + S1 + S2 + tree-generated dimension-5 psi2phi2",
        "loop_order": 1,
        "fixed_order_input": "tree-level EFT1 Wilson coefficients only",
        "scan_mode": (
            "seed_support_only"
            if seed_support_only
            else "L/eC one-loop closure"
        ),
        "metadata": {
            "dS1": int(context.metadata["dS1"]),
            "dS2": int(context.metadata["dS2"]),
            "YS1": context.metadata["YS1"],
            "YS2": context.metadata["YS2"],
            "real_scalar_dimension": (
                context.model.total_real_scalar_dimension
            ),
            "fermion_dimension": context.fermion_basis.dimension,
        },
        "candidate_component_count": len(candidates),
        "initial_independent_component_count": len(initial_support),
        "nonzero_beta_component_count": len(betas),
        "generated_component_count": len(generated),
        "generated_components": [list(item) for item in generated],
        "weinberg_subspace_validation": weinberg_diagnostics,
        "elapsed_seconds": elapsed,
        "betas": {
            _serialise_component(component): {
                name: _expr_text(value)
                for name, value in contributions.items()
            }
            for component, contributions in sorted(betas.items())
        },
    }

    if output_path is not None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            json.dumps(payload, indent=2),
            encoding="utf-8",
        )

    return payload


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Evaluate the complete one-loop EFT1 psi^2 phi^2 master RGE."
        )
    )
    parser.add_argument("wilson_seed_json", type=Path)
    parser.add_argument("quartic_seed_json", type=Path)
    parser.add_argument("rgbeta_json", type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional JSON output path.",
    )
    parser.add_argument(
        "--seed-support-only",
        action="store_true",
        help=(
            "Fast plumbing test: evaluate only components nonzero at the "
            "matching boundary instead of the full L/eC closure."
        ),
    )
    args = parser.parse_args()

    payload = run_eft1_wilson_rge(
        wilson_seed_path=args.wilson_seed_json,
        quartic_seed_path=args.quartic_seed_json,
        rgbeta_path=args.rgbeta_json,
        output_path=args.output,
        seed_support_only=args.seed_support_only,
    )

    summary = {
        key: payload[key]
        for key in (
            "status",
            "scan_mode",
            "candidate_component_count",
            "initial_independent_component_count",
            "nonzero_beta_component_count",
            "generated_component_count",
            "elapsed_seconds",
        )
    }
    print(json.dumps(summary, indent=2))

    if payload["weinberg_subspace_validation"] is not None:
        print(
            json.dumps(
                {
                    "weinberg_subspace_validation":
                        payload["weinberg_subspace_validation"]
                },
                indent=2,
            )
        )

    # Show a few nonzero beta functions without flooding the terminal.
    for component, contributions in list(payload["betas"].items())[:8]:
        print(f"{component}: {contributions['total']}")
