from __future__ import annotations

"""Export exact EFT1 Wilson running into stage-2 Wolfram pieces.

The operator projection has already established

    C_run^(1) = Sum_r a_r O_r + a5 O5

in a gauge-invariant basis.  For threshold 2 it is cleaner to split this as

    heavy piece:
        hbar * Sum_r a_r O_r

    Weinberg piece:
        hbar * a5 O5

because O5 contains only SM fields and therefore does not need to be matched
again when S1,S2 are integrated out.

This exporter writes a Wolfram Language file defining

    EFT1WilsonRunningHeavyInsertion
    EFT1WilsonRunningWeinbergCoefficient

where the first object already includes Matchete's hbar and the second is the
coefficient multiplying hbar * O5.
"""

import argparse
import json
from pathlib import Path
from typing import Any

import sympy as sp
from sympy.printing.mathematica import mathematica_code


def _expr(raw: Any) -> sp.Expr:
    if isinstance(raw, sp.Expr):
        return raw
    return sp.sympify(
        str(raw),
        locals={
            "conjugate": sp.conjugate,
            "sqrt": sp.sqrt,
            "log": sp.log,
            "I": sp.I,
            "pi": sp.pi,
        },
    )


def _wl_expr(raw: Any) -> str:
    """Convert a SymPy-style pipeline expression to valid Wolfram syntax."""
    return mathematica_code(sp.simplify(_expr(raw)))


def _wl_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _load_projection(path: Path) -> dict[str, Any]:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))

    if payload.get("status") != "Success":
        raise ValueError(
            "Operator projection is not exact/successful: "
            f"{payload.get('status')!r}"
        )
    if not payload.get("exact_operator_projection"):
        raise ValueError("Refusing to export an incomplete operator projection.")
    if int(payload.get("residual_component_count", 0)) != 0:
        raise ValueError(
            "Refusing to export projection with nonzero residual components."
        )

    return payload


def export_eft1_wilson_matchete_insertion(
    projection_path: Path,
    output_path: Path,
) -> dict[str, Any]:
    projection = _load_projection(projection_path)

    heavy_terms: list[str] = []
    weinberg_coefficients: list[sp.Expr] = []
    referenced_symbols: set[str] = set()

    for entry in projection.get("operator_coefficients") or []:
        multiplier_expr = sp.simplify(_expr(entry.get("running_multiplier", "0")))
        if multiplier_expr == 0:
            continue

        referenced_symbols.update(str(symbol) for symbol in multiplier_expr.free_symbols)
        kind = entry.get("kind")

        if kind == "tree":
            term = entry.get("term_input_form")
            if not term:
                raise ValueError(
                    f"Tree direction {entry.get('name')} has no TermInputForm."
                )

            heavy_terms.append(f"({_wl_expr(multiplier_expr)})*({term})")

        elif kind == "weinberg":
            weinberg_coefficients.append(multiplier_expr)

        else:
            raise ValueError(f"Unknown operator direction kind: {kind!r}")

    heavy_body = "0" if not heavy_terms else " +\n    ".join(heavy_terms)
    weinberg_coefficient = sp.simplify(sum(weinberg_coefficients, sp.S.Zero))

    scales = projection.get("scales") or {}
    source = Path(projection_path).as_posix()

    referenced_symbol_wl = ", ".join(
        _wl_string(symbol) for symbol in sorted(referenced_symbols)
    )

    wolfram = """(* Auto-generated by EFT1WilsonMatcheteExporter.py

   Fixed-order EFT1 Wilson running, split for threshold 2.

   Heavy-field part:
     EFT1WilsonRunningHeavyInsertion
       = hbar * Sum_r a_r O_r

   Pure-SM Weinberg part:
     EFT1WilsonRunningWeinbergCoefficient
       = a5

   Hence the full running correction is

     Delta L_run =
       EFT1WilsonRunningHeavyInsertion
       + hbar * EFT1WilsonRunningWeinbergCoefficient * O5.

   The a_r and a5 already include Log[muLow/muHigh].

   IMPORTANT:
   The stage-1 O(hbar) matching boundary is NOT included here and must not be
   evolved again.
*)

ClearAll[
  EFT1WilsonRunningHeavyInsertion,
  EFT1WilsonRunningWeinbergCoefficient,
  EFT1WilsonRunningInsertionMetadata
];

EFT1WilsonRunningHeavyInsertion =
  hbar * (
    __HEAVY_BODY__
  );

EFT1WilsonRunningWeinbergCoefficient =
  __WEINBERG_COEFF__;

EFT1WilsonRunningInsertionMetadata = <|
  "SourceProjection" -> __SOURCE__,
  "MuHigh" -> __MU_HIGH__,
  "MuLow" -> __MU_LOW__,
  "LogRatio" -> __LOG_RATIO__,
  "HeavyDirectionCount" -> __HEAVY_COUNT__,
  "WeinbergDirectionCount" -> __WEINBERG_COUNT__,
  "ReferencedPlainSymbols" -> {__REFERENCED_SYMBOLS__},
  "ExactProjection" -> True
|>;
"""

    replacements = {
        "__HEAVY_BODY__": heavy_body,
        "__WEINBERG_COEFF__": _wl_expr(weinberg_coefficient),
        "__SOURCE__": _wl_string(source),
        "__MU_HIGH__": _wl_string(str(scales.get("mu_high", ""))),
        "__MU_LOW__": _wl_string(str(scales.get("mu_low", ""))),
        "__LOG_RATIO__": _wl_string(str(scales.get("log_ratio", ""))),
        "__HEAVY_COUNT__": str(len(heavy_terms)),
        "__WEINBERG_COUNT__": str(len(weinberg_coefficients)),
        "__REFERENCED_SYMBOLS__": referenced_symbol_wl,
    }
    for key, value in replacements.items():
        wolfram = wolfram.replace(key, value)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(wolfram, encoding="utf-8")

    return {
        "status": "Success",
        "output": str(output_path),
        "heavy_direction_count": len(heavy_terms),
        "weinberg_direction_count": len(weinberg_coefficients),
        "weinberg_running_coefficient": str(weinberg_coefficient),
        "log_ratio": scales.get("log_ratio", ""),
        "referenced_plain_symbols": sorted(referenced_symbols),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Export exact EFT1 Wilson running as separate heavy-field and "
            "pure-SM Weinberg Wolfram pieces for threshold 2."
        )
    )
    parser.add_argument("projection_json", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    result = export_eft1_wilson_matchete_insertion(
        projection_path=args.projection_json,
        output_path=args.output,
    )

    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
