from __future__ import annotations

"""Evaluate the general one-loop Weinberg RGE from exported T3 tensors.

This stage consumes ``t3_rge_tensor_exchange.json`` produced by
``T3RGETensorExport.wl``.  It constructs the global Weyl Yukawa tensor and the
complete electroweak Weinberg Wilson tensor, then evaluates the general
psi^2 phi^2 master equation on every L,L,H,H component.  The full BSM quartic
basis is audited, but only its pure-Higgs block is materialized in the real
basis because the current Wilson tensor has support only on L,L,H,H.

The exported fermion basis currently contains L and F but not the quark and
charged-lepton singlet blocks.  Consequently the master-equation result is
completed with the already validated one-generation SM Yukawa baseline
``6|yu|^2 + 6|yd|^2 - |ye|^2``.  This avoids double counting the gauge and
Higgs-quartic terms already generated by the tensor equation.
"""

import argparse
from itertools import product
import json
from pathlib import Path
from typing import Any

import sympy as sp

from RGE.general.GeneralWeinbergRGEGenerator import (
    calculate_master_rge,
    g2,
    with_collinear_anomalous_dimensions,
)
from RGE.general.T3RGETensors import (
    T3RGETensors,
    load_component_exchange,
    quartic_components_from_exchange,
    quartic_tensor_from_components,
    wilson_component_function,
)
from RGE.general.T3YukawaAdapter import real_yukawa_tensor_from_exchange
from RGE.general.WeinbergWilsonAdapter import (
    build_weinberg_wilson_tensor,
    validate_weinberg_tensor_symmetry,
)


def _expression_json(expression: sp.Expr) -> dict[str, str]:
    expression = sp.factor(sp.simplify(expression))
    return {
        "sympy": sp.sstr(expression),
        "latex": sp.latex(expression),
    }


def _is_t3b_ma_exchange(data: dict[str, Any]) -> bool:
    scalars = {entry["name"]: entry for entry in data.get("scalars", [])}
    fermions = {entry["name"]: entry for entry in data.get("raw_fermions", [])}
    try:
        return (
            int(scalars["S1"]["su2_dimension"]) == 2
            and int(scalars["S2"]["su2_dimension"]) == 2
            and int(fermions["F"]["su2_dimension"]) == 1
            and sp.sympify(scalars["S1"]["hypercharge"]) == -sp.Rational(1, 2)
            and sp.sympify(scalars["S2"]["hypercharge"]) == sp.Rational(1, 2)
            and sp.sympify(fermions["F"]["hypercharge"]) == 0
        )
    except (KeyError, TypeError, ValueError):
        return False


def _invariant_metadata_checks(
    data: dict[str, Any],
    complex_quartics,
) -> dict[str, Any]:
    """Check that every exported invariant has its own named coupling."""

    families = data.get("invariant_families")
    if not isinstance(families, list):
        return {
            "metadata_present": False,
            "valid": None,
            "families": [],
            "unexpected_quartic_couplings": [],
        }

    actual_quartic_couplings = {
        symbol.name
        for term in complex_quartics
        for symbol in term.coefficient.free_symbols
        if symbol.name.startswith("lambda")
    }
    expected_quartic_couplings: set[str] = set()

    raw_yukawas = data.get("raw_yukawa_components", [])
    family_results: list[dict[str, Any]] = []

    for family in families:
        name = str(family["family"])
        kind = str(family["kind"])
        expected_count = int(family["expected_physical_count"])
        couplings = [str(value) for value in family.get("couplings", [])]

        count_matches = (
            len(couplings) == expected_count
            and len(set(couplings)) == expected_count
        )

        if kind == "quartic":
            expected_quartic_couplings.update(couplings)
            present_couplings = sorted(
                set(couplings) & actual_quartic_couplings
            )
            exported_invariants = len(present_couplings)
            all_present = set(couplings) <= actual_quartic_couplings
        elif kind == "yukawa":
            entries = [
                entry
                for entry in raw_yukawas
                if str(entry.get("interaction")) == name
            ]
            present_couplings = sorted(
                {str(entry.get("coupling")) for entry in entries}
            )
            invariant_ids = {
                int(entry.get("invariant", 0)) for entry in entries
            }
            exported_invariants = len(invariant_ids)
            all_present = (
                set(couplings) == set(present_couplings)
                and invariant_ids == set(range(1, expected_count + 1))
            )
        else:
            present_couplings = []
            exported_invariants = 0
            all_present = False

        family_results.append(
            {
                "family": name,
                "kind": kind,
                "expected_physical_count": expected_count,
                "exported_invariant_count": exported_invariants,
                "couplings": couplings,
                "present_couplings": present_couplings,
                "distinct_couplings_for_each_invariant": count_matches,
                "all_expected_invariants_exported": all_present,
                "valid": count_matches and all_present,
            }
        )

    unexpected_quartics = sorted(
        actual_quartic_couplings - expected_quartic_couplings
    )
    valid = (
        all(result["valid"] for result in family_results)
        and not unexpected_quartics
    )

    return {
        "metadata_present": True,
        "metadata_version": data.get("invariant_metadata_version"),
        "valid": valid,
        "families": family_results,
        "unexpected_quartic_couplings": unexpected_quartics,
    }


def evaluate_general_t3_weinberg_rge(data: dict[str, Any]) -> dict[str, Any]:
    """Construct all tensors and test closure of the electroweak operator."""

    if int(data.get("schema_version", -1)) != 1:
        raise ValueError("Only T3 RGE tensor-exchange schema version 1 is supported.")

    scalar_model, fermion_basis, yukawa_components = (
        real_yukawa_tensor_from_exchange(data)
    )
    complex_quartics = quartic_components_from_exchange(data)
    invariant_checks = _invariant_metadata_checks(data, complex_quartics)

    # C currently has support only on LLHH.  In the scalar-pair contraction
    # lambda_abcd C_ijcd, both summed scalar indices c,d are therefore Higgs
    # indices, and the requested output indices a,b are Higgs indices too.
    # Portal and BSM-only quartics cannot contribute.  Expanding them into a
    # full real tensor is especially expensive for large representations, so
    # retain them for multiplicity bookkeeping but materialize only V(H).
    higgs_quartics = tuple(
        term
        for term in complex_quartics
        if all(factor.scalar_name == "H" for factor in term.factors)
    )
    higgs_only_model = type(scalar_model)(
        scalars=(scalar_model.block("H").scalar,)
    )
    quartic_components = quartic_tensor_from_components(
        higgs_only_model,
        higgs_quartics,
    )

    kappa = sp.Symbol("kappa")
    wilson_components = build_weinberg_wilson_tensor(
        scalar_model,
        fermion_basis,
        kappa,
    )
    validate_weinberg_tensor_symmetry(wilson_components)
    higgs_index_set = set(scalar_model.block("H").indices)
    if any(
        a not in higgs_index_set or b not in higgs_index_set
        for _, _, a, b in wilson_components
    ):
        raise RuntimeError(
            "Pure-Higgs quartic materialization requires an LLHH-only "
            "Wilson tensor."
        )

    tensors = T3RGETensors(
        scalar_model=scalar_model,
        fermion_basis=fermion_basis,
        yukawa_components=yukawa_components,
        quartic_components=quartic_components,
        wilson_components=wilson_components,
    )
    inputs = tensors.master_inputs()
    # Construct the completed inputs once.  The anomalous-dimension callables
    # memoize their matrix elements, so all LLHH components reuse the same
    # scalar and fermion results instead of recomputing them independently.
    complete_inputs = with_collinear_anomalous_dimensions(
        model=scalar_model,
        inputs=inputs,
    )
    coefficient = wilson_component_function(wilson_components)

    lepton_indices = tuple(fermion_basis.block("L").indices)
    higgs_indices = tuple(scalar_model.block("H").indices)
    nonzero_ratios: list[sp.Expr] = []
    zero_failures: list[dict[str, Any]] = []

    for component in product(
        lepton_indices,
        lepton_indices,
        higgs_indices,
        higgs_indices,
    ):
        total = calculate_master_rge(
            model=scalar_model,
            inputs=complete_inputs,
            output_component=component,
            coefficient=coefficient,
            simplify_each=False,
        )["total"]
        total = sp.simplify(total)

        if component in wilson_components:
            nonzero_ratios.append(
                sp.simplify(total / wilson_components[component])
            )
        elif total != 0:
            zero_failures.append(
                {
                    "component": list(component),
                    "beta": sp.sstr(total),
                }
            )

    if not nonzero_ratios:
        raise RuntimeError("The constructed Weinberg tensor has no nonzero components.")

    common_ratio = sp.factor(nonzero_ratios[0])
    ratio_failures = [
        index
        for index, ratio in enumerate(nonzero_ratios[1:], start=2)
        if sp.simplify(ratio - common_ratio) != 0
    ]

    nu = fermion_basis.global_index("L", 1)
    h0_r = scalar_model.block("H").local_to_global(3)
    representative = (nu, nu, h0_r, h0_r)
    representative_terms = calculate_master_rge(
        model=scalar_model,
        inputs=complete_inputs,
        output_component=representative,
        coefficient=coefficient,
        simplify_each=True,
    )
    representative_c = wilson_components[representative]

    # The general exchange currently omits e_R and the quark multiplets.  Add
    # only their trusted one-generation SM Yukawa contribution.  Gauge and
    # Higgs-quartic terms are already present in common_ratio.
    ye, yu, yd = sp.symbols("ye yu yd", complex=True)
    sm_yukawa_completion = (
        6 * yu * sp.conjugate(yu)
        + 6 * yd * sp.conjugate(yd)
        - ye * sp.conjugate(ye)
    )
    completed_ratio = sp.factor(common_ratio + sm_yukawa_completion)

    ma_result = None
    ma_check = None
    if _is_t3b_ma_exchange(data):
        h = sp.Symbol("h", complex=True)
        y1 = sp.Symbol("y1")
        y2 = sp.Symbol("y2")
        ma_result = sp.factor(
            completed_ratio.subs(
                {
                    y1: sp.conjugate(h),
                    sp.conjugate(y1): h,
                    y2: sp.conjugate(h),
                    sp.conjugate(y2): h,
                },
                simultaneous=True,
            )
        )
        lambda_h = sp.Symbol("lambdaH")
        expected_ma = (
            -3 * g2**2
            + 2 * lambda_h
            + sm_yukawa_completion
            + 2 * h * sp.conjugate(h)
        )
        ma_check = sp.simplify(ma_result - expected_ma) == 0

    higgs = scalar_model.block("H")
    hpr = higgs.local_to_global(1)
    hpi = higgs.local_to_global(2)
    lambda_h = sp.Symbol("lambdaH")
    quartic_normalization_ok = (
        sp.simplify(quartic_components[(hpr, hpr, hpr, hpr)] - 3 * lambda_h)
        == 0
        and sp.simplify(
            quartic_components[tuple(sorted((hpr, hpr, hpi, hpi)))] - lambda_h
        )
        == 0
    )

    success = (
        not ratio_failures
        and not zero_failures
        and quartic_normalization_ok
        and (ma_check is not False)
        and (invariant_checks["valid"] is not False)
    )

    return {
        "status": "Success" if success else "Failed",
        "model_name": data.get("model_name", "T3-general"),
        "schema_version": data["schema_version"],
        "basis": {
            "real_scalar_dimension": scalar_model.total_real_scalar_dimension,
            "weyl_fermion_dimension": fermion_basis.dimension,
        },
        "tensor_counts": {
            "exported_complex_quartic_terms": len(complex_quartics),
            "materialized_complex_higgs_quartic_terms": len(higgs_quartics),
            "nonzero_real_quartic_components": len(quartic_components),
            "nonzero_real_yukawa_components": len(yukawa_components),
            "nonzero_weinberg_components": len(wilson_components),
        },
        "checks": {
            "weinberg_tensor_symmetry": True,
            "higgs_quartic_normalization": quartic_normalization_ok,
            "common_beta_factor_for_all_nonzero_components": not ratio_failures,
            "zero_components_remain_zero": not zero_failures,
            "nonzero_components_checked": len(nonzero_ratios),
            "zero_components_checked": (
                len(lepton_indices) ** 2 * len(higgs_indices) ** 2
                - len(wilson_components)
            ),
            "ratio_failure_indices": ratio_failures,
            "zero_component_failures": zero_failures,
            "ma_bridge_recognized": ma_result is not None,
            "ma_one_generation_check": ma_check,
            "invariant_multiplicity": invariant_checks,
        },
        "representative_component": {
            "indices": list(representative),
            "C_component": _expression_json(representative_c),
            "normalized_contributions": {
                name: _expression_json(value / representative_c)
                for name, value in representative_terms.items()
                if name != "total"
            },
        },
        "beta_kappa_over_kappa": {
            "exported_L_and_F_basis": _expression_json(common_ratio),
            "sm_yukawa_completion": _expression_json(sm_yukawa_completion),
            "complete_one_generation": _expression_json(completed_ratio),
            "ma_bridge": (
                _expression_json(ma_result) if ma_result is not None else None
            ),
        },
        "scope": {
            "calculation": "one-loop running of an LLHH Wilson operator with T3 fields active",
            "quartic_materialization": (
                "Only the pure-Higgs real quartic block is required for an "
                "LLHH-only Wilson tensor; all BSM invariant families remain "
                "present in the multiplicity audit."
            ),
            "not_calculated": "general beta functions for all renormalisable T3 masses and couplings",
            "sm_completion_reason": (
                "The exchange contains L and F only; the validated SM singlet/quark "
                "Yukawa baseline is added after the tensor calculation."
            ),
        },
    }


def run_general_t3_weinberg_rge_stage(
    exchange_path: Path,
    output_path: Path,
) -> dict[str, Any]:
    data = load_component_exchange(exchange_path)
    result = evaluate_general_t3_weinberg_rge(data)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("exchange", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    result = run_general_t3_weinberg_rge_stage(args.exchange, args.output)
    print(f"General T3 Weinberg RGE: {result['status']}")
    print(
        "beta_kappa/kappa = "
        + result["beta_kappa_over_kappa"]["complete_one_generation"]["sympy"]
    )
    invariant_check = result["checks"]["invariant_multiplicity"]
    if invariant_check["metadata_present"]:
        print(
            "Invariant multiplicity: "
            + ("Success" if invariant_check["valid"] else "Failed")
            + f" ({len(invariant_check['families'])} families checked)"
        )
    if result["beta_kappa_over_kappa"]["ma_bridge"] is not None:
        print(
            "Ma bridge = "
            + result["beta_kappa_over_kappa"]["ma_bridge"]["sympy"]
        )
    print(f"Wrote {args.output}")
    return 0 if result["status"] == "Success" else 1


if __name__ == "__main__":
    raise SystemExit(main())
