(* TestT3RGBetaPortalClosure.wl
   Test RG closure of the Higgs-BSM portal sector.

   Current model includes only:
       (H† H)(S† S)

   For S in a non-trivial SU(2) representation there is also an independent
   adjoint-channel contraction:
       (H† T^A H)(S† T^A S)

   We register that missing coupling, compute its one-loop beta function,
   then set the missing coupling itself to zero. A non-zero remainder means
   the restricted scalar potential is not closed under RG evolution.
*)

ClearAll["Global`*"];
Needs["RGBeta`"];

Get[
    FileNameJoin[{
        DirectoryName[$InputFileName],
        "..",
        "..",
        "RGE",
        "running",
        "wolfram",
        "T3RGBetaModel.wl"
    }]
];

ClearAll[
    T3PortalAdjInvariant,
    AddMissingPortal,
    TestPortalClosure
];

T3PortalAdjInvariant[2] :=
    (
        tGen[SU2L @ fund, A, #1, #2] *
        tGen[SU2L @ fund, A, #3, #4] &
    );

T3PortalAdjInvariant[3] :=
    (
        tGen[SU2L @ fund, A, #1, #2] *
        tGen[SU2L @ S2, A, #3, #4] &
    );

AddMissingPortal[
    coupling_,
    scalar_,
    dimension_Integer
] := Module[{},
    SetReal[coupling];

    AddQuartic[
        coupling,
        {Bar @ H, H, Bar @ scalar, scalar},
        GroupInvariant -> T3PortalAdjInvariant[dimension]
    ];
];

TestPortalClosure[
    label_String,
    coupling_,
    scalar_,
    dimension_Integer
] := Module[
    {beta, zeroBeta, residual},

    If[dimension == 1,
        Print["    ", label, ": not applicable (scalar is SU(2) singlet)"];
        Return[];
    ];

    AddMissingPortal[coupling, scalar, dimension];

    beta = CheckAbort[
        Quiet[BetaTerm[coupling, 1]],
        $Aborted
    ];

    If[beta === $Aborted,
        Print["    ", label, ": beta ABORTED"];
        Return[];
    ];

    zeroBeta = Simplify[
        beta /. {
            coupling -> 0,
            Bar[coupling] -> 0
        }
    ];

    residual = DeleteDuplicates @ Cases[
        zeroBeta,
        _del | _delS2 | _fStruct | _tGen | _eps,
        Infinity
    ];

    Print[""];
    Print["    ", label];
    Print["      beta at missing coupling = 0:"];
    Print["      ", InputForm[zeroBeta]];
    Print[
        "      generated by running: ",
        If[TrueQ[zeroBeta === 0], "NO", "YES"]
    ];
    Print["      residual group tensors: ", residual];
];

models = {
    {"A", {1, 3, 2}, 0},
    {"B", {2, 2, 1}, -1},
    {"C", {2, 2, 3}, -1},
    {"D", {3, 1, 2}, -2},
    {"E", {3, 3, 2}, 0}
};

Print[""];
Print["================ T3 PORTAL RG-CLOSURE TEST ================"];

Do[
    label = model[[1]];
    dims = model[[2]];
    alpha = model[[3]];

    Print[""];
    Print[
        "T3-", label,
        ": dims=", dims,
        ", alpha=", alpha
    ];

    build = CheckAbort[
        Quiet[
            T3RGBetaBuild[
                dims[[1]],
                dims[[2]],
                dims[[3]],
                alpha
            ]
        ],
        $Aborted
    ];

    If[!AssociationQ[build],
        Print["  build FAILED"];
        Continue[];
    ];

    Print["  build SUCCESS"];

    TestPortalClosure[
        "missing H-S1 adjoint portal",
        lambdaH1Adj,
        S1,
        dims[[1]]
    ];

    build = Quiet[
        T3RGBetaBuild[
            dims[[1]],
            dims[[2]],
            dims[[3]],
            alpha
        ]
    ];

    TestPortalClosure[
        "missing H-S2 adjoint portal",
        lambdaH2Adj,
        S2,
        dims[[2]]
    ];

    ,
    {model, models}
];

Print[""];
Print["T3 PORTAL RG-CLOSURE TEST: COMPLETE"];
