(* TestT3RGBetaEThirdMixedClosure.wl
   Test the third independent S1-S2 quartic contraction in T3-E.

   For two complex SU(2) triplets,
       3* x 3 = 1 + 3 + 5.

   Therefore
       S1† S1 S2† S2
   admits three singlet contractions.

   Our present basis contains:
     1. singlet-singlet:
          (S1†.S1)(S2†.S2)

     2. adjoint-adjoint:
          (S1† T^A S1)(S2† T^A S2)

   This file probes a third linearly independent contraction.  In the real
   triplet index basis it can be represented by the symmetric crossed pairing

       delta_ac delta_bd + delta_ad delta_bc,

   with field ordering
       {S1†, S1, S2†, S2}.

   It need not be normalized as a pure quintet projector for an RG-closure
   test; it only needs to be linearly independent of the first two structures.
*)

ClearAll["Global`*"];
Needs["RGBeta`"];

Get[
    FileNameJoin[{
        DirectoryName[$InputFileName],
        "..",
        "..",
        "RGE",
        "running",
        "wolfram",
        "T3RGBetaModel.wl"
    }]
];

Print[""];
Print["================ T3-E THIRD MIXED QUARTIC CLOSURE ================"];

build = CheckAbort[
    Quiet[T3RGBetaBuild[3, 3, 2, 0]],
    $Aborted
];

If[!AssociationQ[build],
    Print["base build: FAILED"];
    Exit[1];
];

Print["base build: SUCCESS"];

SetReal[lambda12Cross];

reg = CheckAbort[
    Quiet[
        AddQuartic[
            lambda12Cross,
            {Bar @ S1, S1, Bar @ S2, S2},
            GroupInvariant -> (
                del[SU2L @ S2, #1, #3] *
                del[SU2L @ S2, #2, #4] +
                del[SU2L @ S2, #1, #4] *
                del[SU2L @ S2, #2, #3] &
            )
        ];
        "Success"
    ],
    $Aborted
];

Print["third mixed contraction registration: ", reg];

If[reg =!= "Success",
    Exit[1];
];

beta = CheckAbort[
    Quiet[BetaTerm[lambda12Cross, 1]],
    $Aborted
];

If[beta === $Aborted,
    Print["beta(lambda12Cross): ABORTED"];
    Exit[1];
];

Print["beta(lambda12Cross): SUCCESS"];

zeroBeta = Simplify[
    beta /. {
        lambda12Cross -> 0,
        Bar[lambda12Cross] -> 0
    }
];

residual = DeleteDuplicates @ Cases[
    zeroBeta,
    _del | _delS2 | _fStruct | _tGen | _eps,
    Infinity
];

Print[""];
Print["--- beta at lambda12Cross = 0 ---"];
Print[InputForm[zeroBeta]];

Print[""];
Print[
    "generated by running: ",
    If[TrueQ[zeroBeta === 0], "NO", "YES"]
];

Print["residual group tensors: ", residual];

Print[""];
Print["T3-E THIRD MIXED QUARTIC CLOSURE CHECK: COMPLETE"];
