(* TestT3RGBetaNewFieldStructureClosure.wl
   Probe genuinely new scalar quartic field structures found by the
   gauge+Z2 completeness scan.

   Strategy:
     - use a fresh model for each candidate;
     - register exactly one omitted quartic;
     - compute its one-loop beta;
     - set that coupling itself to zero;
     - report whether a non-zero source remains.

   This is a targeted closure test, not yet an exhaustive basis construction.
*)

ClearAll["Global`*"];
Needs["RGBeta`"];

Get[
    FileNameJoin[{
        DirectoryName[$InputFileName],
        "..",
        "..",
        "RGE",
        "running",
        "wolfram",
        "T3RGBetaModel.wl"
    }]
];

ClearAll[
    TryClosure,
    BuildFresh,
    InvSinglet,
    InvPair,
    InvHHTripletToTriplet
];

InvSinglet := (1 &);

InvPair[1] := (1 &);
InvPair[2] := (del[SU2L @ fund, #1, #2] &);
InvPair[3] := (del[SU2L @ S2, #1, #2] &);

(* H† H pair in singlet channel times another singlet pair. *)
ClearAll[HHdagPairInvariant];
HHdagPairInvariant[1] :=
    (del[SU2L @ fund, #1, #2] &);

(* Symmetric HH or H†H† triplet coupled to two doublets/triplets where needed. *)
ClearAll[HHTripletDoubletInvariant];
HHTripletDoubletInvariant :=
    (
        delS2[SU2L, a, #1, #2] *
        delS2[SU2L, a, #3, #4] &
    );

BuildFresh[dims_List, alpha_Integer] :=
    Quiet[T3RGBetaBuild[dims[[1]], dims[[2]], dims[[3]], alpha]];

TryClosure[
    label_String,
    dims_List,
    alpha_Integer,
    coupling_,
    addFunction_
] := Module[
    {build, reg, beta, zeroBeta, residual},

    Print[""];
    Print["    ", label];

    build = CheckAbort[BuildFresh[dims, alpha], $Aborted];

    If[!AssociationQ[build],
        Print["      build FAILED"];
        Return[];
    ];

    reg = CheckAbort[
        Quiet[
            addFunction[];
            "Success"
        ],
        $Aborted
    ];

    If[reg =!= "Success",
        Print["      registration ABORTED"];
        Return[];
    ];

    beta = CheckAbort[
        Quiet[BetaTerm[coupling, 1]],
        $Aborted
    ];

    If[beta === $Aborted,
        Print["      beta ABORTED"];
        Return[];
    ];

    zeroBeta = Simplify[
        beta /. {
            coupling -> 0,
            Bar[coupling] -> 0
        }
    ];

    residual = DeleteDuplicates @ Cases[
        zeroBeta,
        _del | _delS2 | _fStruct | _tGen | _eps,
        Infinity
    ];

    Print["      beta at missing coupling = 0:"];
    Print["      ", InputForm[zeroBeta]];
    Print[
        "      generated by running: ",
        If[TrueQ[zeroBeta === 0], "NO", "YES"]
    ];
    Print["      residual group tensors: ", residual];
];

models = <|
    "A" -> <|"dims" -> {1,3,2}, "alpha" -> 0|>,
    "B" -> <|"dims" -> {2,2,1}, "alpha" -> -1|>,
    "C" -> <|"dims" -> {2,2,3}, "alpha" -> -1|>,
    "D" -> <|"dims" -> {3,1,2}, "alpha" -> -2|>,
    "E" -> <|"dims" -> {3,3,2}, "alpha" -> 0|>
|>;

Print[""];
Print["================ T3 NEW FIELD-STRUCTURE CLOSURE ================"];

(* ------------------------------------------------------------------ *)
(* T3-A                                                               *)
(* ------------------------------------------------------------------ *)

dims = models["A"]["dims"];
alpha = models["A"]["alpha"];

Print[""];
Print["T3-A"];

TryClosure[
    "S1^4 + h.c.",
    dims, alpha,
    kA_S14,
    Function[{},
        AddQuartic[
            kA_S14,
            {S1, S1, S1, S1},
            GroupInvariant -> (1 &),
            SelfConjugate -> False
        ]
    ]
];

TryClosure[
    "H H† S1†^2 + h.c.",
    dims, alpha,
    kA_HHS12,
    Function[{},
        AddQuartic[
            kA_HHS12,
            {H, Bar @ H, Bar @ S1, Bar @ S1},
            GroupInvariant -> (
                del[SU2L @ fund, #1, #2] &
            ),
            SelfConjugate -> False
        ]
    ]
];

TryClosure[
    "H†^2 S1 S2 + h.c.",
    dims, alpha,
    kA_H2S1S2,
    Function[{},
        AddQuartic[
            kA_H2S1S2,
            {Bar @ H, Bar @ H, S1, S2},
            GroupInvariant -> (
                delS2[SU2L, #4, #1, #2] &
            ),
            SelfConjugate -> False
        ]
    ]
];

(* ------------------------------------------------------------------ *)
(* T3-B and T3-C                                                      *)
(* ------------------------------------------------------------------ *)

Do[
    dims = models[label]["dims"];
    alpha = models[label]["alpha"];

    Print[""];
    Print["T3-", label];

    TryClosure[
        "H†^2 S2^2 + h.c.",
        dims, alpha,
        Symbol["k" <> label <> "_H2S22"],
        With[{c = Symbol["k" <> label <> "_H2S22"]},
            Function[{},
                AddQuartic[
                    c,
                    {Bar @ H, Bar @ H, S2, S2},
                    GroupInvariant -> HHTripletDoubletInvariant,
                    SelfConjugate -> False
                ]
            ]
        ]
    ];

    TryClosure[
        "H†^2 S1†^2 + h.c.",
        dims, alpha,
        Symbol["k" <> label <> "_H2S112"],
        With[{c = Symbol["k" <> label <> "_H2S112"]},
            Function[{},
                AddQuartic[
                    c,
                    {Bar @ H, Bar @ H, Bar @ S1, Bar @ S1},
                    GroupInvariant -> HHTripletDoubletInvariant,
                    SelfConjugate -> False
                ]
            ]
        ]
    ];

    TryClosure[
        "S1†^2 S2†^2 + h.c.",
        dims, alpha,
        Symbol["k" <> label <> "_S12S22"],
        With[{c = Symbol["k" <> label <> "_S12S22"]},
            Function[{},
                AddQuartic[
                    c,
                    {Bar @ S1, Bar @ S1, Bar @ S2, Bar @ S2},
                    GroupInvariant -> (
                        delS2[SU2L, a, #1, #2] *
                        delS2[SU2L, a, #3, #4] &
                    ),
                    SelfConjugate -> False
                ]
            ]
        ]
    ];

    ,
    {label, {"B", "C"}}
];

(* ------------------------------------------------------------------ *)
(* T3-D                                                               *)
(* ------------------------------------------------------------------ *)

dims = models["D"]["dims"];
alpha = models["D"]["alpha"];

Print[""];
Print["T3-D"];

TryClosure[
    "S2^4 + h.c.",
    dims, alpha,
    kD_S24,
    Function[{},
        AddQuartic[
            kD_S24,
            {S2, S2, S2, S2},
            GroupInvariant -> (1 &),
            SelfConjugate -> False
        ]
    ]
];

TryClosure[
    "H H† S2^2 + h.c.",
    dims, alpha,
    kD_HHS22,
    Function[{},
        AddQuartic[
            kD_HHS22,
            {H, Bar @ H, S2, S2},
            GroupInvariant -> (
                del[SU2L @ fund, #1, #2] &
            ),
            SelfConjugate -> False
        ]
    ]
];

TryClosure[
    "H†^2 S1† S2† + h.c.",
    dims, alpha,
    kD_H2S1S2,
    Function[{},
        AddQuartic[
            kD_H2S1S2,
            {Bar @ H, Bar @ H, Bar @ S1, Bar @ S2},
            GroupInvariant -> (
                delS2[SU2L, #3, #1, #2] &
            ),
            SelfConjugate -> False
        ]
    ]
];

(* ------------------------------------------------------------------ *)
(* T3-E                                                               *)
(* ------------------------------------------------------------------ *)

dims = models["E"]["dims"];
alpha = models["E"]["alpha"];

Print[""];
Print["T3-E"];

TryClosure[
    "S1^4 + h.c.",
    dims, alpha,
    kE_S14,
    Function[{},
        AddQuartic[
            kE_S14,
            {S1, S1, S1, S1},
            GroupInvariant -> (
                del[SU2L @ S2, #1, #2] *
                del[SU2L @ S2, #3, #4] &
            ),
            SelfConjugate -> False
        ]
    ]
];

TryClosure[
    "H H† S1†^2 + h.c.",
    dims, alpha,
    kE_HHS12,
    Function[{},
        AddQuartic[
            kE_HHS12,
            {H, Bar @ H, Bar @ S1, Bar @ S1},
            GroupInvariant -> (
                del[SU2L @ fund, #1, #2] *
                del[SU2L @ S2, #3, #4] &
            ),
            SelfConjugate -> False
        ]
    ]
];

TryClosure[
    "H†^2 S1 S2 + h.c.",
    dims, alpha,
    kE_H2S1S2,
    Function[{},
        AddQuartic[
            kE_H2S1S2,
            {Bar @ H, Bar @ H, S1, S2},
            GroupInvariant -> (
                delS2[SU2L, a, #1, #2] *
                T3RGBetaS2TripleInvariant[a, #3, #4] &
            ),
            SelfConjugate -> False
        ]
    ]
];

Print[""];
Print["T3 NEW FIELD-STRUCTURE CLOSURE CHECK: COMPLETE"];
