(* TestT3RGBetaScalarClosure2.wl
   Second RG-closure probe for the T3 scalar potential.

   Tests:
     1. Extra self-quartic for a complex SU(2) triplet:
          (S† T^A S)(S† T^A S)

     2. Extra mixed S1-S2 contraction when both are non-singlets:
          (S1† T^A S1)(S2† T^A S2)

   Each coupling is registered separately on a fresh model, its one-loop beta
   is computed, and then the tested coupling itself is set to zero.
*)

ClearAll["Global`*"];
Needs["RGBeta`"];

Get[
    FileNameJoin[{
        DirectoryName[$InputFileName],
        "..",
        "..",
        "RGE",
        "running",
        "wolfram",
        "T3RGBetaModel.wl"
    }]
];

ClearAll[
    RepFromDimension,
    AddTripletSelfAdj,
    AddMixedAdj,
    ClosureResult
];

RepFromDimension[2] := SU2L @ fund;
RepFromDimension[3] := SU2L @ S2;


AddTripletSelfAdj[coupling_, scalar_] := Module[{},
    SetReal[coupling];

    AddQuartic[
        coupling,
        {Bar @ scalar, scalar, Bar @ scalar, scalar},
        GroupInvariant -> (
            tGen[SU2L @ S2, A, #1, #2] *
            tGen[SU2L @ S2, A, #3, #4] / 2 &
        )
    ];
];


AddMixedAdj[
    coupling_,
    scalar1_,
    dimension1_Integer,
    scalar2_,
    dimension2_Integer
] := Module[{},
    SetReal[coupling];

    AddQuartic[
        coupling,
        {Bar @ scalar1, scalar1, Bar @ scalar2, scalar2},
        GroupInvariant -> (
            tGen[RepFromDimension[dimension1], A, #1, #2] *
            tGen[RepFromDimension[dimension2], A, #3, #4] &
        )
    ];
];


ClosureResult[label_String, coupling_] := Module[
    {beta, zeroBeta, residual},

    beta = CheckAbort[
        Quiet[BetaTerm[coupling, 1]],
        $Aborted
    ];

    If[beta === $Aborted,
        Print["    ", label, ": beta ABORTED"];
        Return[];
    ];

    zeroBeta = Simplify[
        beta /. {
            coupling -> 0,
            Bar[coupling] -> 0
        }
    ];

    residual = DeleteDuplicates @ Cases[
        zeroBeta,
        _del | _delS2 | _fStruct | _tGen | _eps,
        Infinity
    ];

    Print[""];
    Print["    ", label];
    Print["      beta at missing coupling = 0:"];
    Print["      ", InputForm[zeroBeta]];
    Print[
        "      generated by running: ",
        If[TrueQ[zeroBeta === 0], "NO", "YES"]
    ];
    Print["      residual group tensors: ", residual];
];


models = {
    {"A", {1, 3, 2}, 0},
    {"B", {2, 2, 1}, -1},
    {"C", {2, 2, 3}, -1},
    {"D", {3, 1, 2}, -2},
    {"E", {3, 3, 2}, 0}
};


Print[""];
Print["================ T3 SCALAR RG-CLOSURE TEST 2 ================"];

Do[
    label = model[[1]];
    dims = model[[2]];
    alpha = model[[3]];

    Print[""];
    Print[
        "T3-", label,
        ": dims=", dims,
        ", alpha=", alpha
    ];

    (* -------------------------------------------------------------- *)
    (* Extra S1 self quartic if S1 is a triplet                       *)
    (* -------------------------------------------------------------- *)

    If[dims[[1]] == 3,
        build = Quiet[
            T3RGBetaBuild[
                dims[[1]], dims[[2]], dims[[3]], alpha
            ]
        ];

        If[AssociationQ[build],
            result = CheckAbort[
                Quiet[
                    AddTripletSelfAdj[lambdaS1Adj, S1];
                    "Success"
                ],
                $Aborted
            ];

            If[result === "Success",
                ClosureResult[
                    "missing S1 triplet self contraction",
                    lambdaS1Adj
                ],
                Print["    missing S1 triplet self contraction: registration ABORTED"]
            ];
        ];
    ];

    (* -------------------------------------------------------------- *)
    (* Extra S2 self quartic if S2 is a triplet                       *)
    (* -------------------------------------------------------------- *)

    If[dims[[2]] == 3,
        build = Quiet[
            T3RGBetaBuild[
                dims[[1]], dims[[2]], dims[[3]], alpha
            ]
        ];

        If[AssociationQ[build],
            result = CheckAbort[
                Quiet[
                    AddTripletSelfAdj[lambdaS2Adj, S2];
                    "Success"
                ],
                $Aborted
            ];

            If[result === "Success",
                ClosureResult[
                    "missing S2 triplet self contraction",
                    lambdaS2Adj
                ],
                Print["    missing S2 triplet self contraction: registration ABORTED"]
            ];
        ];
    ];

    (* -------------------------------------------------------------- *)
    (* Extra mixed S1-S2 adjoint contraction                          *)
    (* -------------------------------------------------------------- *)

    If[dims[[1]] > 1 && dims[[2]] > 1,
        build = Quiet[
            T3RGBetaBuild[
                dims[[1]], dims[[2]], dims[[3]], alpha
            ]
        ];

        If[AssociationQ[build],
            result = CheckAbort[
                Quiet[
                    AddMixedAdj[
                        lambda12Adj,
                        S1, dims[[1]],
                        S2, dims[[2]]
                    ];
                    "Success"
                ],
                $Aborted
            ];

            If[result === "Success",
                ClosureResult[
                    "missing S1-S2 adjoint contraction",
                    lambda12Adj
                ],
                Print["    missing S1-S2 adjoint contraction: registration ABORTED"]
            ];
        ];
    ];

    ,
    {model, models}
];

Print[""];
Print["T3 SCALAR RG-CLOSURE TEST 2: COMPLETE"];
