from __future__ import annotations

"""Consolidated physical group factors for beta_lambdaH1/H2/lambda12.

This module combines the independently validated portal-quartic backbone,
adjoint-squared recouplings, T3-E Cross/self-adjoint recouplings, and pure
gauge quartic tensors.

It is T3-representation generic for the supported SU(2) dimensions d=1,2,3.
No A--E model label is used as physics input.

Conventions:
    Q = T3 + Y
    Y(H)  = 1/2
    Y(S1) = alpha/2
    Y(S2) = (alpha+2)/2
    C2(d) = (d^2-1)/4
    G_Si  = max(dF,dSi)/dSi

The returned coefficients multiply monomials in 16*pi^2 beta.
"""

from dataclasses import asdict, dataclass
from fractions import Fraction
import argparse
import json


def _txt(x: Fraction) -> str:
    return str(x.numerator) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"


def _c2(d: int) -> Fraction:
    return Fraction(d * d - 1, 4)


def _validate(d1: int, d2: int, dF: int) -> None:
    if min(d1, d2, dF) < 1:
        raise ValueError("SU(2) dimensions must be positive.")
    if d1 not in (1, 2, 3) or d2 not in (1, 2, 3):
        raise ValueError("Current T3 implementation supports scalar dimensions 1,2,3.")
    if abs(d1 - dF) != 1 or abs(d2 - dF) != 1:
        raise ValueError("T3 Yukawa invariance requires dSi=dF+/-1.")


def _pair_su2_gauge_singlet(d1: int, d2: int) -> Fraction:
    """Physical singlet projection of the SU(2) g2^4 tensor in S1-S2 sector."""
    if d1 == 1 or d2 == 1:
        return Fraction(0)
    if d1 == d2 == 2:
        return Fraction(9, 4)
    if d1 == d2 == 3:
        return Fraction(12)
    raise ValueError(f"Unsupported T3 scalar pair ({d1},{d2}).")


def _pair_adj_square_singlet(d1: int, d2: int) -> Fraction:
    """Singlet piece generated by (lambda12Adj)^2."""
    if d1 == 1 or d2 == 1:
        return Fraction(0)
    if d1 == d2 == 2:
        return Fraction(3, 4)
    if d1 == d2 == 3:
        return Fraction(4)
    raise ValueError(f"Unsupported T3 scalar pair ({d1},{d2}).")


@dataclass(frozen=True)
class PortalQuarticBetaGroupFactors:
    dS1: int
    dS2: int
    dF: int
    alpha: int

    GS1: str
    GS2: str
    C2S1: str
    C2S2: str
    YS1: str
    YS2: str

    beta_lambdaH1: dict[str, str]
    beta_lambdaH2: dict[str, str]
    beta_lambda12: dict[str, str]

    # Companion coefficients generated into non-singlet beta functions.
    generated_non_singlet: dict[str, str]


def portal_quartic_beta_group_factors(
    dS1: int,
    dS2: int,
    dF: int,
    alpha: int,
) -> PortalQuarticBetaGroupFactors:
    d1, d2, dF, alpha = map(int, (dS1, dS2, dF, alpha))
    _validate(d1, d2, dF)

    C1 = _c2(d1)
    C2 = _c2(d2)
    CH = Fraction(3, 4)

    YH = Fraction(1, 2)
    Y1 = Fraction(alpha, 2)
    Y2 = Fraction(alpha + 2, 2)

    GS1 = Fraction(max(dF, d1), d1)
    GS2 = Fraction(max(dF, d2), d2)

    h1 = {
        "lambdaH1*Tr_y1": _txt(2 * GS1),
        "lambdaH1*Tr_Yd": "6",
        "lambdaH1*Tr_Ye": "2",
        "lambdaH1*Tr_Yu": "6",
        "Tr_y1Ye": _txt(-2 * GS1),
        "abs_lambdaT3_sq": _txt(Fraction(12, d1)),
        "g2_sq*lambdaH1": _txt(-6 * (CH + C1)),
        "gY_sq*lambdaH1": _txt(-6 * (YH * YH + Y1 * Y1)),
        "lambdaH*lambdaH1": "6",
        "lambdaH1_sq": "4",
        "lambdaH1*lambdaS1": _txt(Fraction(2 * (d1 + 1))),
        "lambda12*lambdaH2": _txt(Fraction(2 * d2)),
        "g2_four": _txt(4 * CH * C1),
        "gY_four": _txt(12 * YH * YH * Y1 * Y1),
    }

    if d1 > 1:
        h1["lambdaH1Adj_sq"] = _txt(C1)
    if d1 == 3:
        h1["lambdaH1*lambdaS1Adj"] = _txt(2 * C1)
    if d1 == d2 == 3:
        h1["lambdaH2*lambda12Cross"] = "4"

    h2 = {
        "lambdaH2*Tr_y2": _txt(2 * GS2),
        "lambdaH2*Tr_Yd": "6",
        "lambdaH2*Tr_Ye": "2",
        "lambdaH2*Tr_Yu": "6",
        "Tr_y2Ye": _txt(-2 * GS2),
        "abs_lambdaT3_sq": _txt(Fraction(12, d2)),
        "g2_sq*lambdaH2": _txt(-6 * (CH + C2)),
        "gY_sq*lambdaH2": _txt(-6 * (YH * YH + Y2 * Y2)),
        "lambdaH*lambdaH2": "6",
        "lambdaH2_sq": "4",
        "lambdaH2*lambdaS2": _txt(Fraction(2 * (d2 + 1))),
        "lambda12*lambdaH1": _txt(Fraction(2 * d1)),
        "g2_four": _txt(4 * CH * C2),
        "gY_four": _txt(12 * YH * YH * Y2 * Y2),
    }

    if d2 > 1:
        h2["lambdaH2Adj_sq"] = _txt(C2)
    if d2 == 3:
        h2["lambdaH2*lambdaS2Adj"] = _txt(2 * C2)
    if d1 == d2 == 3:
        h2["lambdaH1*lambda12Cross"] = "4"

    l12 = {
        "lambda12*Tr_y1": _txt(2 * GS1),
        "lambda12*Tr_y2": _txt(2 * GS2),
        "Tr_y1y2": _txt(-2 * GS1 * GS2),
        "abs_lambdaT3_sq": _txt(Fraction(12, d1 * d2)),
        "g2_sq*lambda12": _txt(-6 * (C1 + C2)),
        "gY_sq*lambda12": _txt(-6 * (Y1 * Y1 + Y2 * Y2)),
        "lambda12_sq": "4",
        "lambda12*lambdaS1": _txt(Fraction(2 * (d1 + 1))),
        "lambda12*lambdaS2": _txt(Fraction(2 * (d2 + 1))),
        "lambdaH1*lambdaH2": "4",
        "g2_four": _txt(_pair_su2_gauge_singlet(d1, d2)),
        "gY_four": _txt(12 * Y1 * Y1 * Y2 * Y2),
    }

    if d1 > 1 and d2 > 1:
        l12["lambda12Adj_sq"] = _txt(_pair_adj_square_singlet(d1, d2))

    if d1 == 3:
        l12["lambda12*lambdaS1Adj"] = _txt(2 * C1)
    if d2 == 3:
        l12["lambda12*lambdaS2Adj"] = _txt(2 * C2)

    if d1 == d2 == 3:
        l12["lambda12Cross_sq"] = "4"
        l12["lambda12Cross*lambdaS1Adj"] = "4"
        l12["lambda12Cross*lambdaS2Adj"] = "4"

    generated = {}
    if d1 > 1:
        generated["beta_lambdaH1Adj:g2sq_gYsq"] = _txt(24 * YH * Y1)
    if d2 > 1:
        generated["beta_lambdaH2Adj:g2sq_gYsq"] = _txt(24 * YH * Y2)
    if d1 > 1 and d2 > 1:
        generated["beta_lambda12Adj:g2sq_gYsq"] = _txt(24 * Y1 * Y2)

    if d1 == d2 == 3:
        generated.update({
            "beta_lambda12Cross:g2_four": "6",
            "beta_lambda12Cross:lambda12Adj_sq": "2",
            "beta_lambda12Cross:lambda12*lambda12Cross": "8",
            "beta_lambda12Cross:lambda12Cross_sq": "10",
            "beta_lambda12Cross:lambda12Cross*lambdaS1Adj": "-2",
            "beta_lambda12Cross:lambda12Cross*lambdaS2Adj": "-2",
        })

    return PortalQuarticBetaGroupFactors(
        dS1=d1,
        dS2=d2,
        dF=dF,
        alpha=alpha,
        GS1=_txt(GS1),
        GS2=_txt(GS2),
        C2S1=_txt(C1),
        C2S2=_txt(C2),
        YS1=_txt(Y1),
        YS2=_txt(Y2),
        beta_lambdaH1=h1,
        beta_lambdaH2=h2,
        beta_lambda12=l12,
        generated_non_singlet=generated,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("dS1", type=int)
    parser.add_argument("dS2", type=int)
    parser.add_argument("dF", type=int)
    parser.add_argument("alpha", type=int)
    args = parser.parse_args()

    result = portal_quartic_beta_group_factors(
        args.dS1, args.dS2, args.dF, args.alpha
    )
    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
