from __future__ import annotations

"""Group-factor decomposition of the one-loop T3 Yukawa beta functions.

This module uses the exact UV Clebsch--Gordan registry together with the
orthonormal-CG conversion implemented in ``YukawaGroupFactors.py``.

For a Yukawa invariant

    y L F S,

with d_L = 2 and d_S = d_F +/- 1, define the canonically normalised CG tensor
C_{a A B}.  Schur's lemma gives three leg contractions,

    sum_{a,A} C_{aAB} C*_{aAB'} = G_S delta_{BB'},
    sum_{A,B} C_{aAB} C*_{a'AB} = G_L delta_{aa'},
    sum_{a,B} C_{aAB} C*_{aA'B} = G_F delta_{AA'}.

With the orthonormal SU(2) CG convention,

    G_S = d_> / d_S,
    G_L = d_> / 2,
    G_F = d_> / d_F,

where d_> = max(d_F,d_S).

For beta_y1, the cubic matrix structures generated by external-leg
renormalisation are therefore

    Tr(y1 y1^dagger) y1 : G_S1
    y1 y1^dagger y1     : 1/2 (G_L1 + G_F1)
    y2 y2^dagger y1     : 1/2 G_L2
    Ye Ye^dagger y1     : 1/2

The y2 cross term enters through the common lepton-doublet leg.  In the
project's vector-like T3 construction y1 and y2 use opposite heavy Weyl
partners, so the y2 correction does not act on the heavy leg of y1.

These formulas reproduce the A--E RGBeta coefficients without fitting any
representation-dependent constants.
"""

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
import sys

import sympy as sp

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from RGE.group_factors.YukawaGroupFactors import (
    y1_scalar_wavefunction_group_factor,
    y2_scalar_wavefunction_group_factor,
)
from RGE.group_factors.YukawaLegFactors import canonical_yukawa_leg_factors


@dataclass(frozen=True)
class YukawaLegFactors:
    dF: int
    dS: int
    d_larger: int
    G_scalar: str
    G_lepton: str
    G_heavy: str
    self_coefficient: str


@dataclass(frozen=True)
class Y1BetaGroupFactors:
    model_dimensions: tuple[int, int, int]
    y1: YukawaLegFactors
    y2: YukawaLegFactors
    trace_y1: str
    self_y1: str
    cross_y2_into_y1: str
    charged_lepton_into_y1: str
    exact_y1_cg_check: bool
    exact_y2_cg_check: bool
    y1_closed_form_residual: str
    y2_closed_form_residual: str


def _serialised_leg_factors(dF: int, dS: int) -> YukawaLegFactors:
    factors = canonical_yukawa_leg_factors(dF, dS)

    return YukawaLegFactors(
        dF=factors.dF,
        dS=factors.dS,
        d_larger=factors.d_larger,
        G_scalar=str(factors.G_scalar),
        G_lepton=str(factors.G_lepton),
        G_heavy=str(factors.G_heavy),
        self_coefficient=str(factors.self_coefficient),
    )


def y1_beta_group_factors(uv_registry: Path) -> Y1BetaGroupFactors:
    payload = json.loads(Path(uv_registry).read_text(encoding="utf-8"))
    meta = payload["metadata"]

    dF = int(meta["dF"])
    dS1 = int(meta["dS1"])
    dS2 = int(meta["dS2"])

    y1 = _serialised_leg_factors(dF, dS1)
    y2 = _serialised_leg_factors(dF, dS2)

    exact_y1 = y1_scalar_wavefunction_group_factor(uv_registry)
    exact_y2 = y2_scalar_wavefunction_group_factor(uv_registry)

    cross = sp.Rational(max(dF, dS2), 4)

    return Y1BetaGroupFactors(
        model_dimensions=(dS1, dS2, dF),
        y1=y1,
        y2=y2,
        trace_y1=y1.G_scalar,
        self_y1=y1.self_coefficient,
        cross_y2_into_y1=str(cross),
        charged_lepton_into_y1="1/2",
        exact_y1_cg_check=(
            exact_y1.canonical_schur_identity_check
            and exact_y1.canonical_minus_closed_form == "0"
        ),
        exact_y2_cg_check=(
            exact_y2.canonical_schur_identity_check
            and exact_y2.canonical_minus_closed_form == "0"
        ),
        y1_closed_form_residual=exact_y1.canonical_minus_closed_form,
        y2_closed_form_residual=exact_y2.canonical_minus_closed_form,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compute the group-factor decomposition of beta_y1."
    )
    parser.add_argument("uv_cg_registry_json", type=Path)
    args = parser.parse_args()

    result = y1_beta_group_factors(args.uv_cg_registry_json)
    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
